### ISSUE TITLE
Outdated copyright year in footer

### ISSUE THREAD

**Issue by m1ci** [dbpedia/databus#206]
In the footer of the page is showing "Copyright 2023". This requires an update to 2025 or ideally make the year dynamically adjust to the current year. 

**Impact:** Displaying an outdated copyright year can appear unmaintained or unprofessional.

---

**Comment by rohan-019** [comment]
Hi, @m1ci 
Could you please assign this issue to me?

**Comment by holycrab13** [comment]
fixed

**Comment by m1ci** [comment]
Still showing old year copyright year -> 2023

Screenshot as of Apr 24,2026 showing "Copyright 2023"

<img width="1440" height="795" alt="Image" src="https://github.com/user-attachments/assets/e2828358-a627-4f8a-9cb0-d754d055f815" />

**Comment by subhrat123** [comment]
@holycrab13 i would like to work on this if its still available.
